export const MAIN_SHOW = {
  BEGINS: 'FETCH_MAIN_SHOW_BEGINS',
  SUCCESS: 'FETCH_MAIN_SHOW_SUCCESS',
  FAILURE: 'FETCH_MAIN_SHOW_FAILURE',
};

export const POPULAR_SHOWS = {
  BEGINS: 'FETCH_POPULAR_SHOWS_BEGINS',
  SUCCESS: 'FETCH_POPULAR_SHOWS_SUCCESS',
  FAILURE: 'FETCH_POPULAR_SHOWS_FAILURE',
};

export const TOP_RATED_SHOWS = {
  BEGINS: 'FETCH_TOP_RATED_SHOWS_BEGINS',
  SUCCESS: 'FETCH_TOP_RATED_SHOWS_SUCCESS',
  FAILURE: 'FETCH_TOP_RATED_SHOWS_FAILURE',
};

export const LATEST_SHOWS = {
  BEGINS: 'FETCH_LATEST_SHOWS_BEGINS',
  SUCCESS: 'FETCH_LATEST_SHOWS_SUCCESS',
  FAILURE: 'FETCH_LATEST_SHOWS_FAILURE',
};
