export const FETCH_MAIN_SHOW_BEGINS = 'FETCH_MAIN_SHOW_BEGINS';
export const FETCH_MAIN_SHOW_SUCCESS = 'FETCH_MAIN_SHOW_SUCCESS';
export const FETCH_MAIN_SHOW_FAILURE = 'FETCH_MAIN_SHOW_FAILURE';

export const FETCH_SHOWS_BEGINS = 'FETCH_SHOWS_BEGINS';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_FAILURE = 'FETCH_SHOWS_FAILURE';
